// Example Worker + container-enabled Durable Object that runs a
// Workspace inside a Cloudflare Container.
//
// The DO is a thin shell over CloudflareContainerBackend: it picks
// the container (this.ctx.container) and the egress fetcher
// (ctx.exports.WorkspaceProxy bound to this DO instance), forwards
// container-bound /ws upgrades back through the backend, and
// otherwise just calls into a single Workspace instance.
//
// Wire shape:
//
//   client ─► Worker /c/<name>/{file,exec}
//              │  (DO RPC)
//              ▼
//        ContainerExample DO ──► Container ──► computerd (:8080)
//              ▲                                │
//              │  ws://computer.internal/ws    │
//              └─── capnweb session ◀─────────────┘

import { DurableObject, tracing } from "cloudflare:workers";

import {
  type DurableObjectStorageLike,
  getWorkspace,
  R2Bucket,
  type WorkspaceOptions,
  WorkspaceProxy,
  withWorkspace,
} from "@cloudflare/computer";
import {
  CloudflareContainerBackend,
  withWorkspaceContainer,
} from "@cloudflare/computer/backends/container";
import { createCloudflareObserver } from "@cloudflare/computer/observe/cloudflare";

// Re-export so the runtime can build a loopback binding for the
// container egress (ctx.exports.WorkspaceProxy below). The class
// itself lives in @cloudflare/computer; the re-export is what
// puts it in the worker's top-level module graph.
export { WorkspaceProxy };

// Env is generated by `wrangler types` into worker-configuration.d.ts.

// ---------------------------------------------------------------
// Durable Object: owns one Workspace backed by one container.
// ---------------------------------------------------------------
// The container half of the DO. The backend lives here rather than on
// ContainerExample because withWorkspace's options callback needs it
// while constructing the Workspace: base-class fields are initialized
// by the time the callback runs, subclass fields are not.
class ContainerBase extends withWorkspaceContainer(class extends DurableObject<Env> {}) {
  readonly backend = new CloudflareContainerBackend({
    container: () => this,
    workspace: { binding: "ContainerExample", id: this.ctx.id.toString() },
    egress: { mode: "direct" },
  });
}

// Named, with an explicit return type: an inline callback would make
// the class's own base expression part of its inferred type.
// DurableObject keeps ctx and env protected, so read them through a
// cast the way the mixin's own docs do.
function workspaceOptions(self: InstanceType<typeof ContainerBase>): WorkspaceOptions {
  const { ctx, env } = self as unknown as { ctx: DurableObjectState; env: Env };
  return {
    // ctx.storage.sql.exec returns a narrower row type than
    // DurableObjectStorageLike declares; the runtime shape
    // matches. Cast through unknown to bypass invariance.
    storage: ctx.storage as unknown as DurableObjectStorageLike,
    backends: [self.backend],
    // Mount the Bucket binding at /workspace/r2. Seed it with
    // `npm run seed:r2` (uploads ./seed/data/hello.txt) so the
    // first read returns "hello world". The bucket is read-only;
    // writes through Workspace.fs under /workspace/r2 reject
    // with EROFS.
    mounts: {
      "/workspace/r2": R2Bucket(env.Bucket),
    },
    // Route every workspace operation through the Cloudflare
    // runtime's user-tracing surface. The runtime owns the span
    // lifecycle; the observer is a thin facade that forwards seed
    // attributes and a `setAttribute` callback. With
    // `observability.traces.enabled = true` in wrangler.jsonc, the
    // spans show up in the Workers Observability dashboard
    // alongside the runtime's automatic fetch and binding spans.
    observer: createCloudflareObserver({ tracing }),
  };
}

// withWorkspace owns the Workspace and installs the prototype
// accessor `getWorkspace` dispatches to. Methods on the client it
// hands back round-trip into this DO; the actual SyncRPC + ShellRPC
// traffic stays on the computerd ↔ DO capnweb wire.
export class ContainerExample extends withWorkspace(ContainerBase, workspaceOptions) {
  // ---- WebSocket: computerd's outbound /ws upgrade ---------------------

  override async fetch(request: Request): Promise<Response> {
    return this.backend.handleFetch(request);
  }
}

// ---------------------------------------------------------------
// Worker HTTP surface (unchanged)
// ---------------------------------------------------------------

interface ExecRequest {
  command?: string;
  argv?: string[];
  cwd?: string;
  encoding?: "utf8";
}

// computerd mounts the VFS at /workspace inside the container. The file
// handler enforces that every path it touches sits under that
// root; callers pass the absolute VFS path verbatim in the URL
// (e.g. PUT /c/<name>/file/workspace/hello.txt writes
// /workspace/hello.txt, exactly as computerd sees it). Anything outside
// /workspace is rejected up front — the example only wants to
// expose the mounted tree, not the container's full filesystem.
const MOUNT_ROOT = "/workspace";

function resolveMountPath(rest: string): string | null {
  // URL was matched as /c/<name>/file/<rest>; treat <rest> as an
  // absolute path with the leading `/` stripped.
  const candidate = `/${rest}`;
  if (candidate !== MOUNT_ROOT && !candidate.startsWith(`${MOUNT_ROOT}/`)) {
    return null;
  }
  // Reject .. segments so a caller can't escape the mount through
  // path traversal once we've validated the prefix.
  if (candidate.split("/").includes("..")) {
    return null;
  }
  return candidate;
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    const fileMatch = url.pathname.match(/^\/c\/([^/]+)\/file\/(.+)$/);
    if (fileMatch) {
      const resolved = resolveMountPath(fileMatch[2]);
      if (resolved === null) {
        return errorJSON(new Error(`path must sit under ${MOUNT_ROOT}; got /${fileMatch[2]}`), 400);
      }
      return handleFile(request, env, fileMatch[1], resolved);
    }

    const execMatch = url.pathname.match(/^\/c\/([^/]+)\/exec\/?$/);
    if (execMatch) return handleExec(request, env, execMatch[1]);

    if (url.pathname === "/" || url.pathname === "") {
      return new Response(
        [
          "container example",
          "",
          `  PUT  /c/<name>/file/workspace/<path>     write file at ${MOUNT_ROOT}/<path>`,
          `  GET  /c/<name>/file/workspace/<path>     read file at ${MOUNT_ROOT}/<path>`,
          "  POST /c/<name>/exec                      run a command (JSON result)",

          "",
        ].join("\n"),
        { headers: { "content-type": "text/plain" } },
      );
    }

    return new Response("not found", { status: 404 });
  },
} satisfies ExportedHandler<Env>;

async function handleFile(
  request: Request,
  env: Env,
  name: string,
  path: string,
): Promise<Response> {
  const stub = env.ContainerExample.get(env.ContainerExample.idFromName(name));
  // `wrangler types` doesn't surface the accessor the withWorkspace
  // mixin installs, so cast at the boundary.
  const ws = await getWorkspace(stub as unknown as Parameters<typeof getWorkspace>[0]);

  if (request.method === "PUT") {
    const body = new Uint8Array(await request.arrayBuffer());
    try {
      await ws.fs.writeFile(path, body);
      return new Response(null, { status: 204 });
    } catch (error) {
      return errorJSON(error, 500);
    }
  }

  if (request.method === "GET") {
    try {
      const stream = await ws.fs.readFile(path, {});
      return new Response(stream, {
        status: 200,
        headers: { "content-type": "application/octet-stream" },
      });
    } catch (error) {
      const code = (error as { code?: string }).code;
      if (code === "ENOENT") return errorJSON(error, 404);
      return errorJSON(error, 500);
    }
  }

  return new Response("method not allowed", { status: 405, headers: { allow: "GET, PUT" } });
}

async function handleExec(request: Request, env: Env, name: string): Promise<Response> {
  if (request.method !== "POST") {
    return new Response("method not allowed", { status: 405, headers: { allow: "POST" } });
  }
  let body: ExecRequest;
  try {
    body = (await request.json()) as ExecRequest;
  } catch {
    return errorJSON(new Error("invalid JSON body"), 400);
  }

  let command: string;
  if (typeof body.command === "string" && body.command.length > 0) {
    command = body.command;
  } else if (Array.isArray(body.argv) && body.argv.length > 0) {
    command = body.argv.map(shellQuote).join(" ");
  } else {
    return errorJSON(new Error("must provide command or argv"), 400);
  }

  const stub = env.ContainerExample.get(env.ContainerExample.idFromName(name));
  const ws = await getWorkspace(stub as unknown as Parameters<typeof getWorkspace>[0]);
  try {
    const handle = await ws.runtime.exec(command, { cwd: body.cwd, encoding: "utf8" });
    const result = await handle.result();
    return new Response(JSON.stringify(result), {
      status: 200,
      headers: { "content-type": "application/json" },
    });
  } catch (error) {
    return errorJSON(error, 500);
  }
}

function errorJSON(error: unknown, status: number): Response {
  const message = error instanceof Error ? error.message : String(error);
  const code = (error as { code?: string }).code;
  return new Response(JSON.stringify({ error: message, code }), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function shellQuote(arg: string): string {
  if (/^[A-Za-z0-9_\-+=:,./@%]+$/.test(arg)) return arg;
  return `'${arg.replace(/'/g, "'\\''")}'`;
}
