import { useEffect, useMemo, useState } from 'react'
import Plot from 'react-plotly.js'
import { AlertCircle, RefreshCw } from 'lucide-react'
import { getUQResults } from '../utils/api'
import { PageHeader, MetricTile, SectionLabel, Surface, StatusTag } from '../components/ResearchUI'

const configs = [['Compression_ratio','π','总压比','var(--teal)'],['Efficiency','η','等熵效率','var(--yellow)'],['Massflow','ṁ','质量流量','var(--rust)']]
function Panel({ data, keyName, symbol, label, color }) { const rows = data || []; const trueKey = `${keyName}_true`; const predKey = `${keyName}_pred`; const lowerKey = `${keyName}_lower`; const upperKey = `${keyName}_upper`; const covered = rows.filter(r => r[trueKey] >= r[lowerKey] && r[trueKey] <= r[upperKey]).length; const coverage = rows.length ? covered / rows.length * 100 : 0; const ordered = [...rows].sort((a,b) => a[trueKey] - b[trueKey]); return <Surface><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><span style={{ color, font: '20px var(--display)' }}>{symbol}</span><span style={{ color: 'var(--paper)', marginLeft: 10 }}>{label}</span></div><StatusTag tone={coverage < 80 ? 'gold' : 'teal'}>覆盖率 {coverage.toFixed(0)}%</StatusTag></div><Plot data={[{ x: ordered.map((_,i)=>i), y: ordered.map(r=>r[upperKey]), mode:'lines', line:{color:'transparent'}, showlegend:false },{ x: ordered.map((_,i)=>i), y: ordered.map(r=>r[lowerKey]), mode:'lines', fill:'tonexty', fillcolor:'rgba(134,185,170,.10)', line:{color:'transparent'}, showlegend:false },{ x: ordered.map((_,i)=>i), y: ordered.map(r=>r[trueKey]), mode:'lines', name:'真实值', line:{color:'#e6ebe1',width:1.5} },{ x: ordered.map((_,i)=>i), y: ordered.map(r=>r[predKey]), mode:'lines', name:'预测均值', line:{color, width:1.5, dash:'dot'} }]} layout={{ height:220, margin:{l:45,r:10,t:18,b:38}, paper_bgcolor:'rgba(0,0,0,0)', plot_bgcolor:'rgba(0,0,0,0)', font:{color:'#8f9d93',size:10}, xaxis:{showgrid:false,title:'测试样本'}, yaxis:{gridcolor:'rgba(143,157,147,.12)'}, legend:{orientation:'h',x:0,y:1.16,font:{size:9}} }} config={{displayModeBar:false,responsive:true}} useResizeHandler style={{width:'100%',marginTop:10}} /></Surface> }
export default function UQPage() { const [data,setData]=useState(null); const [error,setError]=useState(null); useEffect(()=>{getUQResults().then(r=>setData(r.results)).catch(e=>setError(e.message))},[]); const overall=useMemo(()=>data ? configs.map(([k])=>{const trueKey=`${k}_true`, predKey=`${k}_pred`, err=data.map(r=>Math.abs(r[predKey]-r[trueKey])); return { k, mae:err.reduce((a,b)=>a+b,0)/err.length }}) : [],[data]); if(error)return <div style={{padding:100,textAlign:'center',color:'var(--rust)'}}><AlertCircle /> {error}</div>; if(!data)return <div style={{padding:100,textAlign:'center',color:'var(--muted)'}}><RefreshCw className="spin" /></div>; return <main style={{maxWidth:1240,margin:'0 auto',padding:'58px 28px 90px'}}><PageHeader index="04" tag="不确定性 · UNCERTAINTY" title="知道模型何时没把握" en="Know when the model is uncertain" lead="UQ 用来提示模型信心，不是给出严格的统计保证。这里把覆盖率直接放在图表旁边。" /><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:18}}><StatusTag>训练期 MC Dropout σ</StatusTag><StatusTag tone="gold">名义 95% 区间</StatusTag><StatusTag tone="rust">η 实测覆盖率约 65%</StatusTag></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginBottom:14}}>{overall.map(({k,mae})=>{const item=configs.find(x=>x[0]===k);return <MetricTile key={k} value={mae.toFixed(5)} label={`${item[1]} ${item[2]} MAE`} note="HELD-OUT TEST SET" tone={k==='Efficiency'?'gold':'teal'} />})}</div><section style={{display:'grid',gap:14}}>{configs.map(([k,s,l,c])=><Panel key={k} data={data} keyName={k} symbol={s} label={l} color={c}/>)}</section><Surface style={{marginTop:14}}><SectionLabel>如何阅读 · HOW TO READ</SectionLabel><p style={{color:'var(--muted)',fontSize:13,lineHeight:1.85,marginTop:14}}>区间变宽，说明模型对该区域的认知更弱。覆盖率低于名义水平并不意味着页面坏了，而是提醒你不要把代理输出当成物理事实。最终判断仍需真实 CFD 或 RANS。</p></Surface></main> }
